apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ./efk/charts/elasticsearch
    repoURL: 'https://github.com/maciejgrosz/chess-openings-helmcharts.git'
    targetRevision: HEAD
    # directory:
    #   recurse: true 

  project: default
